### ISSUE TITLE
Chooses wrong edge on divided road

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/loki#52]
GET /route?json={%22locations%22:[{%22lat%22:40.58573429442473,%22lon%22:-80.03710895776749,%22type%22:%22break%22},{%22lat%22:40.58528616196848,%22lon%22:-80.03714650869368,%22type%22:%22break%22}],%22costing%22:%22auto%22}&api_key= HTTP/1.1

The origin is directly on the east bound carriageway of McKnight Rd but an edge on the westbound carriageway is chosen as the origin.

**Comment by kevinkreiser** [comment]
I have seen this before, and made a note of it. Should have put it in issue then. Thanks for doing this!

**Comment by kevinkreiser** [comment]
this is happening because of the node snapping tolerance. basically there are a ton of nodes there on both carriageways. at that exact point its really close to a node on the other side of the carriage way and therefore it snaps to it.

we have a few options.

1. stop node snapping when edge searching is desired
2. only node snap to certain nodes when edge searching is desired

i'll take a look at these
